version: '3'

services:
  # MySQL
  db:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd-desafio-labs
      MYSQL_USER: elias
      MYSQL_PASSWORD: 12345
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3307:3306'
    volumes:
      - my-db:/var/lib/mysql

  api:
    container_name: api
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
volumes:
  my-db: